"""This code is generated by designer"""

#The place where the code is edited are marked as edited


from PyQt5 import QtCore, QtGui, QtWidgets
from b import Ui_window2

class Ui_window1(object):
    def setupUi(self, window1):
        window1.setObjectName("window1")
        window1.resize(279, 209)
        self.centralwidget = QtWidgets.QWidget(window1)
        self.centralwidget.setObjectName("centralwidget")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(80, 50, 91, 51))
        self.next.setObjectName("next")
        window1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 279, 21))
        self.menubar.setObjectName("menubar")
        window1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window1)
        self.statusbar.setObjectName("statusbar")
        window1.setStatusBar(self.statusbar)

        self.retranslateUi(window1)
        QtCore.QMetaObject.connectSlotsByName(window1)

        #Edited line
        self.next.clicked.connect(self.window2)

    def retranslateUi(self, window1):
        _translate = QtCore.QCoreApplication.translate
        window1.setWindowTitle(_translate("window1", "MainWindow"))
        self.next.setText(_translate("window1", "Next"))

    #These two functions windows2 and loopfn are Added
    def window2(self):

        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_window2()
        self.ui.setupUi(self.window2)
        window1.hide()
        self.window2.show()

        self.back = QtWidgets.QPushButton()
        self.ui.back.clicked.connect(self.loopfn)

    def loopfn(self):
        self.window2.hide()
        window1.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window1 = QtWidgets.QMainWindow()
    ui = Ui_window1()
    ui.setupUi(window1)
    window1.show()
    sys.exit(app.exec_())
